LOCK TABLES `data_platform_local_region_local_region_data` WRITE;

INSERT INTO `data_platform_local_region_local_region_data` (`LocalRegion`, `Country`, `GlobalRegion`)
VALUES
    ('01', 'JP', 'AS');
    ('02', 'JP', 'AS');
    ('03', 'JP', 'AS');
    ('04', 'JP', 'AS');
    ('05', 'JP', 'AS');
    ('06', 'JP', 'AS');
    ('07', 'JP', 'AS');
    ('08', 'JP', 'AS');
    ('09', 'JP', 'AS');
    ('10', 'JP', 'AS');
    ('11', 'JP', 'AS');
    ('12', 'JP', 'AS');
    ('13', 'JP', 'AS');
    ('14', 'JP', 'AS');
    ('15', 'JP', 'AS');
    ('16', 'JP', 'AS');
    ('17', 'JP', 'AS');
    ('18', 'JP', 'AS');
    ('19', 'JP', 'AS');
    ('20', 'JP', 'AS');
    ('21', 'JP', 'AS');
    ('22', 'JP', 'AS');
    ('23', 'JP', 'AS');
    ('24', 'JP', 'AS');
    ('25', 'JP', 'AS');
    ('26', 'JP', 'AS');
    ('27', 'JP', 'AS');
    ('28', 'JP', 'AS');
    ('29', 'JP', 'AS');
    ('30', 'JP', 'AS');
    ('31', 'JP', 'AS');
    ('32', 'JP', 'AS');
    ('33', 'JP', 'AS');
    ('34', 'JP', 'AS');
    ('35', 'JP', 'AS');
    ('36', 'JP', 'AS');
    ('37', 'JP', 'AS');
    ('38', 'JP', 'AS');
    ('39', 'JP', 'AS');
    ('40', 'JP', 'AS');
    ('41', 'JP', 'AS');
    ('42', 'JP', 'AS');
    ('43', 'JP', 'AS');
    ('44', 'JP', 'AS');
    ('45', 'JP', 'AS');
    ('46', 'JP', 'AS');
    ('47', 'JP', 'AS');
UNLOCK TABLES;